/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testndk_Good */

#ifndef _Included_com_example_testndk_Good
#define _Included_com_example_testndk_Good
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testndk_Good
 * Method:    testx
 * Signature: ()Ljava/lang/String;
 */JNIEXPORT jstring JNICALL Java_com_example_testndk_Good_testx(JNIEnv *,
		jobject);

#ifdef __cplusplus
}
#endif
#endif
